trigger: none

pool:
  name: adresh

variables:
  serviceConnection: 'akhilesh27may'
  resourceGroup: 'c1apgenikatestlele'
  storageAccount: 'capstora2'
  containerName: 'pipetest27'
  tfStateKey: 'capstora.tfstate'

stages:

# ---------------------------
# 1. FORMAT
# ---------------------------
- stage: FMT
  displayName: "Terraform Format"
  jobs:
  - job: fmt
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - script: |
        terraform fmt -recursive
      displayName: "Auto Format Terraform"

    - script: |
        terraform fmt -check -recursive
      displayName: "Verify Format"

# ---------------------------
# 2. VALIDATE + INIT
# ---------------------------
- stage: VALIDATE
  dependsOn: FMT
  jobs:
  - job: validate
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccount)
        backendAzureRmContainerName: $(containerName)
        backendAzureRmKey: $(tfStateKey)

    - task: TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'

# ---------------------------
# 3. SECURITY SCAN
# ---------------------------
- stage: SECURITY
  dependsOn: VALIDATE
  jobs:
  - job: security
    steps:

    - powershell: |
        choco install tfsec -y
        tfsec .
      displayName: "TFSEC Scan"

# ---------------------------
# 4. PLAN
# ---------------------------
- stage: PLAN
  dependsOn: SECURITY
  jobs:
  - job: plan
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccount)
        backendAzureRmContainerName: $(containerName)
        backendAzureRmKey: $(tfStateKey)

    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: $(serviceConnection)

# ---------------------------
# 5. APPLY
# ---------------------------
- stage: APPLY
  dependsOn: PLAN
  condition: succeeded()
  jobs:
  - job: apply
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccount)
        backendAzureRmContainerName: $(containerName)
        backendAzureRmKey: $(tfStateKey)

    - task: TerraformTask@5
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: $(serviceConnection)
        args: '-auto-approve'